# Generated by Django 3.0.6 on 2020-05-11 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Weekday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu', models.TextField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('weekday', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meals_planer.Weekday')),
            ],
        ),
    ]
